### ISSUE TITLE
Improvement to `list_groups` arguments

### ISSUE THREAD

**Issue by WardLT** [sirosen/globus-nexus-client#3]
The behavior of the input arguments to `list_groups` is a little un-intuitive. Calling to `list_groups` with `for_all_identities=True` does not return the groups for all linked identities, but `for_all_identities='true'` does. I'd like to adjust this code to make the function arguments more intuitive, but do not know where I should make the change. 

What would you recommend? Should converting the input argument from a boolean to a string be something I should write specifically for `list_groups`, something I change in `merge_params` in Globus SDK, or something else?

**Comment by sirosen** [comment]
I didn't notice this issue at all, but I haven't explicitly tested for it.

I want to confirm these behaviors independently, but assuming that it behaves the way you say, it should definitely be special-cased here and not handled by `merge_params`.

`merge_params` is also used for assembling JSON documents to send (wherein `"true"` and `true` are quite different).
There are many different ways APIs can interpret their query params. The net result of this change would be sending Nexus `for_all_identities=true` vs `for_all_identities=True` in the query params.
I think it's easy to make the case both that it should accept both and that we should send whichever one the API has chosen to respect.

I'll do an update to depend on the latest SDK version and handle this when I get time.
